cabal-version:   3.12

-- ^ 3.12: highest version supported by cabal2nix (used by haskell-flake); HLS 2.13 supports up to 3.14
name:            tick-tock-tui
version:         1.0.1
synopsis:        Get latest Bitcoin data in your terminal.
stability:       stable
homepage:        https://github.com/sectore/tick-tock-tui
license:         MIT
license-file:    LICENSE
author:          Jens Krause

-- maintainer:
-- copyright:
category:        TUI
tested-with:     GHC ==9.12
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

library
  import:             warnings
  exposed-modules:    TUI
  other-modules:
    Paths_tick_tock_tui
    TUI.Attr
    TUI.Config
    TUI.Events
    TUI.Service.API
    TUI.Service.Common
    TUI.Service.Kraken
    TUI.Service.Mempool
    TUI.Service.Types
    TUI.Storage
    TUI.Types
    TUI.Utils
    TUI.Widgets.App
    TUI.Widgets.Block
    TUI.Widgets.Converter
    TUI.Widgets.Countdown
    TUI.Widgets.Dashboard
    TUI.Widgets.Fees
    TUI.Widgets.Footer
    TUI.Widgets.Header
    TUI.Widgets.Loader
    TUI.Widgets.Price
    TUI.Widgets.Ratio

  default-extensions:
    NoImportQualifiedPost
    OverloadedStrings

  build-depends:
    , aeson                 >=2.3.0.0
    , async
    , base                  ^>=4.21.0.0
    , brick                 ^>=2.12
    , bytestring
    , directory
    , filepath
    , http-conduit          >=2.3.9.1
    , microlens             >=0.5.0.0
    , microlens-mtl
    , microlens-th
    , mtl
    , optparse-applicative
    , stm
    , text
    , time
    , transformers
    , unordered-containers
    , vty
    , vty-crossplatform

  hs-source-dirs:     src
  default-language:   GHC2024

executable tick-tock-tui
  import:             warnings
  main-is:            Main.hs

  -- other-modules:
  default-extensions: NoImportQualifiedPost
  build-depends:
    , base           ^>=4.21.0.0
    , tick-tock-tui

  hs-source-dirs:     app
  ghc-options:        -threaded -Wcompat -O2
  default-language:   GHC2024

test-suite tick-tock-tui-test
  import:             warnings
  default-language:   GHC2024
  other-modules:
    TUI.Service.Types
    TUI.Types
    TUI.Utils

  default-extensions:
    NoImportQualifiedPost
    OverloadedStrings

  type:               exitcode-stdio-1.0
  hs-source-dirs:     test src
  main-is:            Main.hs
  build-depends:
    , aeson                 >=2.3.0.0
    , base                  ^>=4.21.0.0
    , brick                 ^>=2.12
    , hspec
    , microlens             >=0.5.0.0
    , microlens-th
    , mtl
    , stm
    , text
    , tick-tock-tui
    , time
    , unordered-containers
    , vty
