name: release

on:
  push:
    branches:
      - "release/**"

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      name: ${{ steps.version.outputs.name }}
    steps:
      - uses: actions/checkout@v6
      - name: Get name/version from *.cabal
        id: version
        run: |
          NAME=$(awk '/^name:/ {print $2}' *.cabal)
          VERSION=$(awk '/^version:/ {print $2}' *.cabal)
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.os_target }} on ${{ matrix.os }}
    needs: get-version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os_target: linux
            arch: x86_64
          - os: macos-latest
            os_target: macos
            arch: aarch64
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21

      - name: Build
        run: nix build

      - name: Create archive
        run: |
          mkdir -p artifacts
          ARCHIVE_NAME="${{ needs.get-version.outputs.name }}-${{ needs.get-version.outputs.version }}-${{ matrix.os_target }}_${{ matrix.arch }}.tar.gz"
          tar -czf artifacts/$ARCHIVE_NAME -C result/bin ${{ needs.get-version.outputs.name }}
          cd artifacts
          sha256sum $ARCHIVE_NAME > $ARCHIVE_NAME.sha256

      - name: Upload archive
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os_target }}-build
          path: |
            artifacts/*.tar.gz
            artifacts/*.sha256
          overwrite: true

  create-release:
    name: Create draft release
    needs: [get-version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
          merge-multiple: true

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: "v${{ needs.get-version.outputs.version }}"
          name: "v${{ needs.get-version.outputs.version }}"
          body: Draft release generated by CI.
          files: artifacts/**/*
